### ISSUE TITLE
No such file or directory on source/sink directory since v2

### ISSUE THREAD

**Issue by tduboys** [ovh/beamium#106]
Hi,
Since v2, I've random crashs with this error :
`CRIT could not scan source directory, error: No such file or directory (os error 2)`
or
`CRIT could not scan source directory, error: No such file or directory (os error 2), dir: /opt/beamium/sinks, sink: source`
Just after that, systemd tries to restart beamium.

It's visible on systemd journal.

Our setup uses a collectd source and source/sink directories on the filesystem (not tmpfs).

**Comment by FlorentinDUBOIS** [comment]
resolve with PR #108
